name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Get dependencies
        run: go get -v
      - name: Run Test
        run: go run main.go -search="example.example"
      - name: Build Test
        run: go build .
      - name: Run the build
        run: ./network-database -search="example.example"
